### ISSUE TITLE
show time with +8 timezone instead of default

### ISSUE THREAD

**Issue by paradite** [remember-loved/remember-web#13]

**Comment by franklingu** [comment]
why this is so important? i mean we do not necessarily limit ourselves to be within asia all the time. just kidding. we can just mention that is standard time or change to +8 and mention it is SG time

**Comment by paradite** [comment]
hi, i really want to discuss this with u but now it's 13pm and i need to go eat lunch.

**Comment by franklingu** [comment]
@kmoazzam , you want to give it a try? [stackoverflow, more like a hack](http://stackoverflow.com/questions/439630/how-do-you-create-a-javascript-date-object-with-a-set-timezone-without-using-a-s) ,  [another one](http://stackoverflow.com/questions/10087819/convert-date-to-another-timezone-in-javascript) , [standard one](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse)

**Comment by paradite** [comment]
it's not the problem of creating, it's when u display, u just need to display in +8

**Comment by franklingu** [comment]
yes. agreed @paradite and I did not think I brought up any objection anywhere
