### ISSUE TITLE
sort the timing consistently

### ISSUE THREAD

**Issue by paradite** [remember-loved/remember-web#14]
now within one day the order is ascending, but the days are descending.

**Comment by paradite** [comment]
Longitute: 103.77544003; Latitude: 1.29916241
2015-03-30 13:03:02
Longitute: 103.77544003; Latitude: 1.29916241
2015-03-30 13:03:18
Longitute: 103.77544003; Latitude: 1.29916241
2015-03-30 13:03:33
Longitute: 103.77544003; Latitude: undefined
2015-03-29 14:39:18
Longitute: 103.77544003; Latitude: undefined
2015-03-29 14:39:29

**Comment by franklingu** [comment]
this issue is most likely related to [mongoose issue 1367](https://github.com/Automattic/mongoose/issues/1367)

**Comment by franklingu** [comment]
a quick fix would be stop using descending order for all the records. will continue exploring

**Comment by paradite** [comment]
i don't see how it is related the mongoose, just sorting date and time, not missing items.

**Comment by franklingu** [comment]
anyway, i will look into this

**Comment by franklingu** [comment]
well, I am not sure, but it seems related to the front end logic. a quick fix will be applied
